# Generated by Django 3.1.4 on 2020-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=50)),
                ('orgao_julgador', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=50)),
                ('assunto_principal', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
